version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth-micro-app
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
